// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: messages.proto
// </auto-generated>
#pragma warning disable 1591, 0612, 3021
#region Designer generated code

using pb = global::Google.Protobuf;
using pbc = global::Google.Protobuf.Collections;
using pbr = global::Google.Protobuf.Reflection;
using scg = global::System.Collections.Generic;
namespace StorageCloud {

  /// <summary>Holder for reflection information generated from messages.proto</summary>
  public static partial class MessagesReflection {

    #region Descriptor
    /// <summary>File descriptor for messages.proto</summary>
    public static pbr::FileDescriptor Descriptor {
      get { return descriptor; }
    }
    private static pbr::FileDescriptor descriptor;

    static MessagesReflection() {
      byte[] descriptorData = global::System.Convert.FromBase64String(
          string.Concat(
            "Cg5tZXNzYWdlcy5wcm90bxIMU3RvcmFnZUNsb3VkImAKBVBhcmFtEg8KB3Bh",
            "cmFtSWQYASABKAkSEwoJU1BhcmFtVmFsGAIgASgJSAASEwoJSVBhcmFtVmFs",
            "GAMgASgDSAASEwoJQlBhcmFtVmFsGAQgASgMSABCBwoFdmFsdWUicwoHQ29t",
            "bWFuZBInCgR0eXBlGAEgASgOMhkuU3RvcmFnZUNsb3VkLkNvbW1hbmRUeXBl",
            "EiMKBnBhcmFtcxgCIAMoCzITLlN0b3JhZ2VDbG91ZC5QYXJhbRIMCgRsaXN0",
            "GAMgAygJEgwKBGRhdGEYBCABKAwimwEKDkVuY29kZWRNZXNzYWdlEhAKCGRh",
            "dGFTaXplGAEgASgEEjIKDWhhc2hBbGdvcml0aG0YAiABKA4yGy5TdG9yYWdl",
            "Q2xvdWQuSGFzaEFsZ29yaXRobRIMCgRoYXNoGAMgASgMEicKBHR5cGUYBCAB",
            "KA4yGS5TdG9yYWdlQ2xvdWQuTWVzc2FnZVR5cGUSDAoEZGF0YRgFIAEoDCJL",
            "CglIYW5kc2hha2USPgoTZW5jcnlwdGlvbkFsZ29yaXRobRgBIAEoDjIhLlN0",
            "b3JhZ2VDbG91ZC5FbmNyeXB0aW9uQWxnb3JpdGhtIkkKBEZpbGUSDAoEbmFt",
            "ZRgBIAEoCRIMCgRzaXplGAIgASgDEiUKCG1ldGFkYXRhGAMgAygLMhMuU3Rv",
            "cmFnZUNsb3VkLlBhcmFtIqEBCg5TZXJ2ZXJSZXNwb25zZRIoCgR0eXBlGAEg",
            "ASgOMhouU3RvcmFnZUNsb3VkLlJlc3BvbnNlVHlwZRIjCgZwYXJhbXMYAiAD",
            "KAsyEy5TdG9yYWdlQ2xvdWQuUGFyYW0SDAoEbGlzdBgDIAMoCRIkCghmaWxl",
            "TGlzdBgEIAMoCzISLlN0b3JhZ2VDbG91ZC5GaWxlEgwKBGRhdGEYBSABKAwq",
            "aAoLQ29tbWFuZFR5cGUSCQoFTlVMTDEQABIJCgVMT0dJThABEgsKB1JFTE9H",
            "SU4QAhIKCgZMT0dPVVQQAxIMCghSRUdJU1RFUhAEEgwKCEdFVF9TVEFUEAUS",
            "DgoKTElTVF9GSUxFUxAGKlsKDUhhc2hBbGdvcml0aG0SCQoFTlVMTDIQABIM",
            "CghIX05PSEFTSBABEgwKCEhfU0hBMjU2EAISDAoISF9TSEE1MTIQAxIKCgZI",
            "X1NIQTEQBBIJCgVIX01ENRAFKkkKC01lc3NhZ2VUeXBlEgkKBU5VTEwzEAAS",
            "CwoHQ09NTUFORBABEhMKD1NFUlZFUl9SRVNQT05TRRACEg0KCUhBTkRTSEFL",
            "RRADKj4KE0VuY3J5cHRpb25BbGdvcml0aG0SCQoFTlVMTDQQABIQCgxOT0VO",
            "Q1JZUFRJT04QARIKCgZDQUVTQVIQAip1CgxSZXNwb25zZVR5cGUSCQoFTlVM",
            "TDUQABIGCgJPSxABEgkKBUVSUk9SEAISCgoGTE9HR0VEEAMSCAoEU1RBVBAE",
            "EgkKBUZJTEVTEAUSCgoGU0hBUkVEEAYSDAoIU1JWX0RBVEEQBxIMCghDQU5f",
            "U0VORBAIYgZwcm90bzM="));
      descriptor = pbr::FileDescriptor.FromGeneratedCode(descriptorData,
          new pbr::FileDescriptor[] { },
          new pbr::GeneratedClrTypeInfo(new[] {typeof(global::StorageCloud.CommandType), typeof(global::StorageCloud.HashAlgorithm), typeof(global::StorageCloud.MessageType), typeof(global::StorageCloud.EncryptionAlgorithm), typeof(global::StorageCloud.ResponseType), }, new pbr::GeneratedClrTypeInfo[] {
            new pbr::GeneratedClrTypeInfo(typeof(global::StorageCloud.Param), global::StorageCloud.Param.Parser, new[]{ "ParamId", "SParamVal", "IParamVal", "BParamVal" }, new[]{ "Value" }, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StorageCloud.Command), global::StorageCloud.Command.Parser, new[]{ "Type", "Params", "List", "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StorageCloud.EncodedMessage), global::StorageCloud.EncodedMessage.Parser, new[]{ "DataSize", "HashAlgorithm", "Hash", "Type", "Data" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StorageCloud.Handshake), global::StorageCloud.Handshake.Parser, new[]{ "EncryptionAlgorithm" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StorageCloud.File), global::StorageCloud.File.Parser, new[]{ "Name", "Size", "Metadata" }, null, null, null),
            new pbr::GeneratedClrTypeInfo(typeof(global::StorageCloud.ServerResponse), global::StorageCloud.ServerResponse.Parser, new[]{ "Type", "Params", "List", "FileList", "Data" }, null, null, null)
          }));
    }
    #endregion

  }
  #region Enums
  public enum CommandType {
    [pbr::OriginalName("NULL1")] Null1 = 0,
    [pbr::OriginalName("LOGIN")] Login = 1,
    [pbr::OriginalName("RELOGIN")] Relogin = 2,
    [pbr::OriginalName("LOGOUT")] Logout = 3,
    [pbr::OriginalName("REGISTER")] Register = 4,
    [pbr::OriginalName("GET_STAT")] GetStat = 5,
    [pbr::OriginalName("LIST_FILES")] ListFiles = 6,
  }

  public enum HashAlgorithm {
    [pbr::OriginalName("NULL2")] Null2 = 0,
    [pbr::OriginalName("H_NOHASH")] HNohash = 1,
    [pbr::OriginalName("H_SHA256")] HSha256 = 2,
    [pbr::OriginalName("H_SHA512")] HSha512 = 3,
    [pbr::OriginalName("H_SHA1")] HSha1 = 4,
    [pbr::OriginalName("H_MD5")] HMd5 = 5,
  }

  public enum MessageType {
    [pbr::OriginalName("NULL3")] Null3 = 0,
    [pbr::OriginalName("COMMAND")] Command = 1,
    [pbr::OriginalName("SERVER_RESPONSE")] ServerResponse = 2,
    [pbr::OriginalName("HANDSHAKE")] Handshake = 3,
  }

  public enum EncryptionAlgorithm {
    [pbr::OriginalName("NULL4")] Null4 = 0,
    [pbr::OriginalName("NOENCRYPTION")] Noencryption = 1,
    [pbr::OriginalName("CAESAR")] Caesar = 2,
  }

  public enum ResponseType {
    [pbr::OriginalName("NULL5")] Null5 = 0,
    [pbr::OriginalName("OK")] Ok = 1,
    [pbr::OriginalName("ERROR")] Error = 2,
    [pbr::OriginalName("LOGGED")] Logged = 3,
    [pbr::OriginalName("STAT")] Stat = 4,
    [pbr::OriginalName("FILES")] Files = 5,
    [pbr::OriginalName("SHARED")] Shared = 6,
    [pbr::OriginalName("SRV_DATA")] SrvData = 7,
    [pbr::OriginalName("CAN_SEND")] CanSend = 8,
  }

  #endregion

  #region Messages
  public sealed partial class Param : pb::IMessage<Param> {
    private static readonly pb::MessageParser<Param> _parser = new pb::MessageParser<Param>(() => new Param());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Param> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StorageCloud.MessagesReflection.Descriptor.MessageTypes[0]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Param() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Param(Param other) : this() {
      paramId_ = other.paramId_;
      switch (other.ValueCase) {
        case ValueOneofCase.SParamVal:
          SParamVal = other.SParamVal;
          break;
        case ValueOneofCase.IParamVal:
          IParamVal = other.IParamVal;
          break;
        case ValueOneofCase.BParamVal:
          BParamVal = other.BParamVal;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Param Clone() {
      return new Param(this);
    }

    /// <summary>Field number for the "paramId" field.</summary>
    public const int ParamIdFieldNumber = 1;
    private string paramId_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string ParamId {
      get { return paramId_; }
      set {
        paramId_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "SParamVal" field.</summary>
    public const int SParamValFieldNumber = 2;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string SParamVal {
      get { return valueCase_ == ValueOneofCase.SParamVal ? (string) value_ : ""; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        valueCase_ = ValueOneofCase.SParamVal;
      }
    }

    /// <summary>Field number for the "IParamVal" field.</summary>
    public const int IParamValFieldNumber = 3;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long IParamVal {
      get { return valueCase_ == ValueOneofCase.IParamVal ? (long) value_ : 0L; }
      set {
        value_ = value;
        valueCase_ = ValueOneofCase.IParamVal;
      }
    }

    /// <summary>Field number for the "BParamVal" field.</summary>
    public const int BParamValFieldNumber = 4;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString BParamVal {
      get { return valueCase_ == ValueOneofCase.BParamVal ? (pb::ByteString) value_ : pb::ByteString.Empty; }
      set {
        value_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
        valueCase_ = ValueOneofCase.BParamVal;
      }
    }

    private object value_;
    /// <summary>Enum of possible cases for the "value" oneof.</summary>
    public enum ValueOneofCase {
      None = 0,
      SParamVal = 2,
      IParamVal = 3,
      BParamVal = 4,
    }
    private ValueOneofCase valueCase_ = ValueOneofCase.None;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ValueOneofCase ValueCase {
      get { return valueCase_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void ClearValue() {
      valueCase_ = ValueOneofCase.None;
      value_ = null;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Param);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Param other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (ParamId != other.ParamId) return false;
      if (SParamVal != other.SParamVal) return false;
      if (IParamVal != other.IParamVal) return false;
      if (BParamVal != other.BParamVal) return false;
      if (ValueCase != other.ValueCase) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (ParamId.Length != 0) hash ^= ParamId.GetHashCode();
      if (valueCase_ == ValueOneofCase.SParamVal) hash ^= SParamVal.GetHashCode();
      if (valueCase_ == ValueOneofCase.IParamVal) hash ^= IParamVal.GetHashCode();
      if (valueCase_ == ValueOneofCase.BParamVal) hash ^= BParamVal.GetHashCode();
      hash ^= (int) valueCase_;
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (ParamId.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(ParamId);
      }
      if (valueCase_ == ValueOneofCase.SParamVal) {
        output.WriteRawTag(18);
        output.WriteString(SParamVal);
      }
      if (valueCase_ == ValueOneofCase.IParamVal) {
        output.WriteRawTag(24);
        output.WriteInt64(IParamVal);
      }
      if (valueCase_ == ValueOneofCase.BParamVal) {
        output.WriteRawTag(34);
        output.WriteBytes(BParamVal);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (ParamId.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(ParamId);
      }
      if (valueCase_ == ValueOneofCase.SParamVal) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(SParamVal);
      }
      if (valueCase_ == ValueOneofCase.IParamVal) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(IParamVal);
      }
      if (valueCase_ == ValueOneofCase.BParamVal) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(BParamVal);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Param other) {
      if (other == null) {
        return;
      }
      if (other.ParamId.Length != 0) {
        ParamId = other.ParamId;
      }
      switch (other.ValueCase) {
        case ValueOneofCase.SParamVal:
          SParamVal = other.SParamVal;
          break;
        case ValueOneofCase.IParamVal:
          IParamVal = other.IParamVal;
          break;
        case ValueOneofCase.BParamVal:
          BParamVal = other.BParamVal;
          break;
      }

      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            ParamId = input.ReadString();
            break;
          }
          case 18: {
            SParamVal = input.ReadString();
            break;
          }
          case 24: {
            IParamVal = input.ReadInt64();
            break;
          }
          case 34: {
            BParamVal = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  /// <summary>
  /// TODO uzupelnic wszystkie typy
  /// </summary>
  public sealed partial class Command : pb::IMessage<Command> {
    private static readonly pb::MessageParser<Command> _parser = new pb::MessageParser<Command>(() => new Command());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Command> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StorageCloud.MessagesReflection.Descriptor.MessageTypes[1]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Command() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Command(Command other) : this() {
      type_ = other.type_;
      params_ = other.params_.Clone();
      list_ = other.list_.Clone();
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Command Clone() {
      return new Command(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::StorageCloud.CommandType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::StorageCloud.CommandType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "params" field.</summary>
    public const int ParamsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::StorageCloud.Param> _repeated_params_codec
        = pb::FieldCodec.ForMessage(18, global::StorageCloud.Param.Parser);
    private readonly pbc::RepeatedField<global::StorageCloud.Param> params_ = new pbc::RepeatedField<global::StorageCloud.Param>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::StorageCloud.Param> Params {
      get { return params_; }
    }

    /// <summary>Field number for the "list" field.</summary>
    public const int ListFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_list_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> list_ = new pbc::RepeatedField<string>();
    /// <summary>
    /// u¿ywane do list plików/u¿ytkowników/etc
    /// </summary>
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> List {
      get { return list_; }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 4;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Command);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Command other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if(!params_.Equals(other.params_)) return false;
      if(!list_.Equals(other.list_)) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      hash ^= params_.GetHashCode();
      hash ^= list_.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      params_.WriteTo(output, _repeated_params_codec);
      list_.WriteTo(output, _repeated_list_codec);
      if (Data.Length != 0) {
        output.WriteRawTag(34);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      size += params_.CalculateSize(_repeated_params_codec);
      size += list_.CalculateSize(_repeated_list_codec);
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Command other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      params_.Add(other.params_);
      list_.Add(other.list_);
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            type_ = (global::StorageCloud.CommandType) input.ReadEnum();
            break;
          }
          case 18: {
            params_.AddEntriesFrom(input, _repeated_params_codec);
            break;
          }
          case 26: {
            list_.AddEntriesFrom(input, _repeated_list_codec);
            break;
          }
          case 34: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class EncodedMessage : pb::IMessage<EncodedMessage> {
    private static readonly pb::MessageParser<EncodedMessage> _parser = new pb::MessageParser<EncodedMessage>(() => new EncodedMessage());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<EncodedMessage> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StorageCloud.MessagesReflection.Descriptor.MessageTypes[2]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EncodedMessage() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EncodedMessage(EncodedMessage other) : this() {
      dataSize_ = other.dataSize_;
      hashAlgorithm_ = other.hashAlgorithm_;
      hash_ = other.hash_;
      type_ = other.type_;
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public EncodedMessage Clone() {
      return new EncodedMessage(this);
    }

    /// <summary>Field number for the "dataSize" field.</summary>
    public const int DataSizeFieldNumber = 1;
    private ulong dataSize_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ulong DataSize {
      get { return dataSize_; }
      set {
        dataSize_ = value;
      }
    }

    /// <summary>Field number for the "hashAlgorithm" field.</summary>
    public const int HashAlgorithmFieldNumber = 2;
    private global::StorageCloud.HashAlgorithm hashAlgorithm_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::StorageCloud.HashAlgorithm HashAlgorithm {
      get { return hashAlgorithm_; }
      set {
        hashAlgorithm_ = value;
      }
    }

    /// <summary>Field number for the "hash" field.</summary>
    public const int HashFieldNumber = 3;
    private pb::ByteString hash_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Hash {
      get { return hash_; }
      set {
        hash_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 4;
    private global::StorageCloud.MessageType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::StorageCloud.MessageType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 5;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as EncodedMessage);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(EncodedMessage other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (DataSize != other.DataSize) return false;
      if (HashAlgorithm != other.HashAlgorithm) return false;
      if (Hash != other.Hash) return false;
      if (Type != other.Type) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (DataSize != 0UL) hash ^= DataSize.GetHashCode();
      if (HashAlgorithm != 0) hash ^= HashAlgorithm.GetHashCode();
      if (Hash.Length != 0) hash ^= Hash.GetHashCode();
      if (Type != 0) hash ^= Type.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (DataSize != 0UL) {
        output.WriteRawTag(8);
        output.WriteUInt64(DataSize);
      }
      if (HashAlgorithm != 0) {
        output.WriteRawTag(16);
        output.WriteEnum((int) HashAlgorithm);
      }
      if (Hash.Length != 0) {
        output.WriteRawTag(26);
        output.WriteBytes(Hash);
      }
      if (Type != 0) {
        output.WriteRawTag(32);
        output.WriteEnum((int) Type);
      }
      if (Data.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (DataSize != 0UL) {
        size += 1 + pb::CodedOutputStream.ComputeUInt64Size(DataSize);
      }
      if (HashAlgorithm != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) HashAlgorithm);
      }
      if (Hash.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Hash);
      }
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(EncodedMessage other) {
      if (other == null) {
        return;
      }
      if (other.DataSize != 0UL) {
        DataSize = other.DataSize;
      }
      if (other.HashAlgorithm != 0) {
        HashAlgorithm = other.HashAlgorithm;
      }
      if (other.Hash.Length != 0) {
        Hash = other.Hash;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            DataSize = input.ReadUInt64();
            break;
          }
          case 16: {
            hashAlgorithm_ = (global::StorageCloud.HashAlgorithm) input.ReadEnum();
            break;
          }
          case 26: {
            Hash = input.ReadBytes();
            break;
          }
          case 32: {
            type_ = (global::StorageCloud.MessageType) input.ReadEnum();
            break;
          }
          case 42: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  public sealed partial class Handshake : pb::IMessage<Handshake> {
    private static readonly pb::MessageParser<Handshake> _parser = new pb::MessageParser<Handshake>(() => new Handshake());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<Handshake> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StorageCloud.MessagesReflection.Descriptor.MessageTypes[3]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Handshake() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Handshake(Handshake other) : this() {
      encryptionAlgorithm_ = other.encryptionAlgorithm_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public Handshake Clone() {
      return new Handshake(this);
    }

    /// <summary>Field number for the "encryptionAlgorithm" field.</summary>
    public const int EncryptionAlgorithmFieldNumber = 1;
    private global::StorageCloud.EncryptionAlgorithm encryptionAlgorithm_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::StorageCloud.EncryptionAlgorithm EncryptionAlgorithm {
      get { return encryptionAlgorithm_; }
      set {
        encryptionAlgorithm_ = value;
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as Handshake);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(Handshake other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (EncryptionAlgorithm != other.EncryptionAlgorithm) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (EncryptionAlgorithm != 0) hash ^= EncryptionAlgorithm.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (EncryptionAlgorithm != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) EncryptionAlgorithm);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (EncryptionAlgorithm != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) EncryptionAlgorithm);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(Handshake other) {
      if (other == null) {
        return;
      }
      if (other.EncryptionAlgorithm != 0) {
        EncryptionAlgorithm = other.EncryptionAlgorithm;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            encryptionAlgorithm_ = (global::StorageCloud.EncryptionAlgorithm) input.ReadEnum();
            break;
          }
        }
      }
    }

  }

  public sealed partial class File : pb::IMessage<File> {
    private static readonly pb::MessageParser<File> _parser = new pb::MessageParser<File>(() => new File());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<File> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StorageCloud.MessagesReflection.Descriptor.MessageTypes[4]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public File() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public File(File other) : this() {
      name_ = other.name_;
      size_ = other.size_;
      metadata_ = other.metadata_.Clone();
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public File Clone() {
      return new File(this);
    }

    /// <summary>Field number for the "name" field.</summary>
    public const int NameFieldNumber = 1;
    private string name_ = "";
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public string Name {
      get { return name_; }
      set {
        name_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    /// <summary>Field number for the "size" field.</summary>
    public const int SizeFieldNumber = 2;
    private long size_;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public long Size {
      get { return size_; }
      set {
        size_ = value;
      }
    }

    /// <summary>Field number for the "metadata" field.</summary>
    public const int MetadataFieldNumber = 3;
    private static readonly pb::FieldCodec<global::StorageCloud.Param> _repeated_metadata_codec
        = pb::FieldCodec.ForMessage(26, global::StorageCloud.Param.Parser);
    private readonly pbc::RepeatedField<global::StorageCloud.Param> metadata_ = new pbc::RepeatedField<global::StorageCloud.Param>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::StorageCloud.Param> Metadata {
      get { return metadata_; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as File);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(File other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Name != other.Name) return false;
      if (Size != other.Size) return false;
      if(!metadata_.Equals(other.metadata_)) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Name.Length != 0) hash ^= Name.GetHashCode();
      if (Size != 0L) hash ^= Size.GetHashCode();
      hash ^= metadata_.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Name.Length != 0) {
        output.WriteRawTag(10);
        output.WriteString(Name);
      }
      if (Size != 0L) {
        output.WriteRawTag(16);
        output.WriteInt64(Size);
      }
      metadata_.WriteTo(output, _repeated_metadata_codec);
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Name.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeStringSize(Name);
      }
      if (Size != 0L) {
        size += 1 + pb::CodedOutputStream.ComputeInt64Size(Size);
      }
      size += metadata_.CalculateSize(_repeated_metadata_codec);
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(File other) {
      if (other == null) {
        return;
      }
      if (other.Name.Length != 0) {
        Name = other.Name;
      }
      if (other.Size != 0L) {
        Size = other.Size;
      }
      metadata_.Add(other.metadata_);
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 10: {
            Name = input.ReadString();
            break;
          }
          case 16: {
            Size = input.ReadInt64();
            break;
          }
          case 26: {
            metadata_.AddEntriesFrom(input, _repeated_metadata_codec);
            break;
          }
        }
      }
    }

  }

  public sealed partial class ServerResponse : pb::IMessage<ServerResponse> {
    private static readonly pb::MessageParser<ServerResponse> _parser = new pb::MessageParser<ServerResponse>(() => new ServerResponse());
    private pb::UnknownFieldSet _unknownFields;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pb::MessageParser<ServerResponse> Parser { get { return _parser; } }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public static pbr::MessageDescriptor Descriptor {
      get { return global::StorageCloud.MessagesReflection.Descriptor.MessageTypes[5]; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    pbr::MessageDescriptor pb::IMessage.Descriptor {
      get { return Descriptor; }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerResponse() {
      OnConstruction();
    }

    partial void OnConstruction();

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerResponse(ServerResponse other) : this() {
      type_ = other.type_;
      params_ = other.params_.Clone();
      list_ = other.list_.Clone();
      fileList_ = other.fileList_.Clone();
      data_ = other.data_;
      _unknownFields = pb::UnknownFieldSet.Clone(other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public ServerResponse Clone() {
      return new ServerResponse(this);
    }

    /// <summary>Field number for the "type" field.</summary>
    public const int TypeFieldNumber = 1;
    private global::StorageCloud.ResponseType type_ = 0;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public global::StorageCloud.ResponseType Type {
      get { return type_; }
      set {
        type_ = value;
      }
    }

    /// <summary>Field number for the "params" field.</summary>
    public const int ParamsFieldNumber = 2;
    private static readonly pb::FieldCodec<global::StorageCloud.Param> _repeated_params_codec
        = pb::FieldCodec.ForMessage(18, global::StorageCloud.Param.Parser);
    private readonly pbc::RepeatedField<global::StorageCloud.Param> params_ = new pbc::RepeatedField<global::StorageCloud.Param>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::StorageCloud.Param> Params {
      get { return params_; }
    }

    /// <summary>Field number for the "list" field.</summary>
    public const int ListFieldNumber = 3;
    private static readonly pb::FieldCodec<string> _repeated_list_codec
        = pb::FieldCodec.ForString(26);
    private readonly pbc::RepeatedField<string> list_ = new pbc::RepeatedField<string>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<string> List {
      get { return list_; }
    }

    /// <summary>Field number for the "fileList" field.</summary>
    public const int FileListFieldNumber = 4;
    private static readonly pb::FieldCodec<global::StorageCloud.File> _repeated_fileList_codec
        = pb::FieldCodec.ForMessage(34, global::StorageCloud.File.Parser);
    private readonly pbc::RepeatedField<global::StorageCloud.File> fileList_ = new pbc::RepeatedField<global::StorageCloud.File>();
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pbc::RepeatedField<global::StorageCloud.File> FileList {
      get { return fileList_; }
    }

    /// <summary>Field number for the "data" field.</summary>
    public const int DataFieldNumber = 5;
    private pb::ByteString data_ = pb::ByteString.Empty;
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public pb::ByteString Data {
      get { return data_; }
      set {
        data_ = pb::ProtoPreconditions.CheckNotNull(value, "value");
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override bool Equals(object other) {
      return Equals(other as ServerResponse);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public bool Equals(ServerResponse other) {
      if (ReferenceEquals(other, null)) {
        return false;
      }
      if (ReferenceEquals(other, this)) {
        return true;
      }
      if (Type != other.Type) return false;
      if(!params_.Equals(other.params_)) return false;
      if(!list_.Equals(other.list_)) return false;
      if(!fileList_.Equals(other.fileList_)) return false;
      if (Data != other.Data) return false;
      return Equals(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override int GetHashCode() {
      int hash = 1;
      if (Type != 0) hash ^= Type.GetHashCode();
      hash ^= params_.GetHashCode();
      hash ^= list_.GetHashCode();
      hash ^= fileList_.GetHashCode();
      if (Data.Length != 0) hash ^= Data.GetHashCode();
      if (_unknownFields != null) {
        hash ^= _unknownFields.GetHashCode();
      }
      return hash;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public override string ToString() {
      return pb::JsonFormatter.ToDiagnosticString(this);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void WriteTo(pb::CodedOutputStream output) {
      if (Type != 0) {
        output.WriteRawTag(8);
        output.WriteEnum((int) Type);
      }
      params_.WriteTo(output, _repeated_params_codec);
      list_.WriteTo(output, _repeated_list_codec);
      fileList_.WriteTo(output, _repeated_fileList_codec);
      if (Data.Length != 0) {
        output.WriteRawTag(42);
        output.WriteBytes(Data);
      }
      if (_unknownFields != null) {
        _unknownFields.WriteTo(output);
      }
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public int CalculateSize() {
      int size = 0;
      if (Type != 0) {
        size += 1 + pb::CodedOutputStream.ComputeEnumSize((int) Type);
      }
      size += params_.CalculateSize(_repeated_params_codec);
      size += list_.CalculateSize(_repeated_list_codec);
      size += fileList_.CalculateSize(_repeated_fileList_codec);
      if (Data.Length != 0) {
        size += 1 + pb::CodedOutputStream.ComputeBytesSize(Data);
      }
      if (_unknownFields != null) {
        size += _unknownFields.CalculateSize();
      }
      return size;
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(ServerResponse other) {
      if (other == null) {
        return;
      }
      if (other.Type != 0) {
        Type = other.Type;
      }
      params_.Add(other.params_);
      list_.Add(other.list_);
      fileList_.Add(other.fileList_);
      if (other.Data.Length != 0) {
        Data = other.Data;
      }
      _unknownFields = pb::UnknownFieldSet.MergeFrom(_unknownFields, other._unknownFields);
    }

    [global::System.Diagnostics.DebuggerNonUserCodeAttribute]
    public void MergeFrom(pb::CodedInputStream input) {
      uint tag;
      while ((tag = input.ReadTag()) != 0) {
        switch(tag) {
          default:
            _unknownFields = pb::UnknownFieldSet.MergeFieldFrom(_unknownFields, input);
            break;
          case 8: {
            type_ = (global::StorageCloud.ResponseType) input.ReadEnum();
            break;
          }
          case 18: {
            params_.AddEntriesFrom(input, _repeated_params_codec);
            break;
          }
          case 26: {
            list_.AddEntriesFrom(input, _repeated_list_codec);
            break;
          }
          case 34: {
            fileList_.AddEntriesFrom(input, _repeated_fileList_codec);
            break;
          }
          case 42: {
            Data = input.ReadBytes();
            break;
          }
        }
      }
    }

  }

  #endregion

}

#endregion Designer generated code
