// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

public interface CommandOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StorageCloud.Command)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .StorageCloud.CommandType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .StorageCloud.CommandType type = 1;</code>
   */
  pl.edu.pw.elka.llepak.tinbox.protobuf.CommandType getType();

  /**
   * <code>repeated .StorageCloud.Param params = 2;</code>
   */
  java.util.List<pl.edu.pw.elka.llepak.tinbox.protobuf.Param> 
      getParamsList();
  /**
   * <code>repeated .StorageCloud.Param params = 2;</code>
   */
  pl.edu.pw.elka.llepak.tinbox.protobuf.Param getParams(int index);
  /**
   * <code>repeated .StorageCloud.Param params = 2;</code>
   */
  int getParamsCount();

  /**
   * <pre>
   * u¿ywane do list plików/u¿ytkowników/etc
   * </pre>
   *
   * <code>repeated string list = 3;</code>
   */
  java.util.List<String>
      getListList();
  /**
   * <pre>
   * u¿ywane do list plików/u¿ytkowników/etc
   * </pre>
   *
   * <code>repeated string list = 3;</code>
   */
  int getListCount();
  /**
   * <pre>
   * u¿ywane do list plików/u¿ytkowników/etc
   * </pre>
   *
   * <code>repeated string list = 3;</code>
   */
  java.lang.String getList(int index);
  /**
   * <pre>
   * u¿ywane do list plików/u¿ytkowników/etc
   * </pre>
   *
   * <code>repeated string list = 3;</code>
   */
  com.google.protobuf.ByteString
      getListBytes(int index);

  /**
   * <code>optional bytes data = 4;</code>
   */
  com.google.protobuf.ByteString getData();
}
