// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

/**
 * Protobuf enum {@code StorageCloud.CommandType}
 */
public enum CommandType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>NULL1 = 0;</code>
   */
  NULL1(0),
  /**
   * <code>LOGIN = 1;</code>
   */
  LOGIN(1),
  /**
   * <code>RELOGIN = 2;</code>
   */
  RELOGIN(2),
  /**
   * <code>LOGOUT = 3;</code>
   */
  LOGOUT(3),
  /**
   * <code>REGISTER = 4;</code>
   */
  REGISTER(4),
  /**
   * <code>GET_STAT = 5;</code>
   */
  GET_STAT(5),
  /**
   * <pre>
   * TODO uzupelnic wszystkie typy
   * </pre>
   *
   * <code>LIST_FILES = 6;</code>
   */
  LIST_FILES(6),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NULL1 = 0;</code>
   */
  public static final int NULL1_VALUE = 0;
  /**
   * <code>LOGIN = 1;</code>
   */
  public static final int LOGIN_VALUE = 1;
  /**
   * <code>RELOGIN = 2;</code>
   */
  public static final int RELOGIN_VALUE = 2;
  /**
   * <code>LOGOUT = 3;</code>
   */
  public static final int LOGOUT_VALUE = 3;
  /**
   * <code>REGISTER = 4;</code>
   */
  public static final int REGISTER_VALUE = 4;
  /**
   * <code>GET_STAT = 5;</code>
   */
  public static final int GET_STAT_VALUE = 5;
  /**
   * <pre>
   * TODO uzupelnic wszystkie typy
   * </pre>
   *
   * <code>LIST_FILES = 6;</code>
   */
  public static final int LIST_FILES_VALUE = 6;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static CommandType valueOf(int value) {
    return forNumber(value);
  }

  public static CommandType forNumber(int value) {
    switch (value) {
      case 0: return NULL1;
      case 1: return LOGIN;
      case 2: return RELOGIN;
      case 3: return LOGOUT;
      case 4: return REGISTER;
      case 5: return GET_STAT;
      case 6: return LIST_FILES;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      CommandType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
          public CommandType findValueByNumber(int number) {
            return CommandType.forNumber(number);
          }
        };

  private final int value;

  private CommandType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:StorageCloud.CommandType)
}

