// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

public interface EncodedMessageOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StorageCloud.EncodedMessage)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional uint64 dataSize = 1;</code>
   */
  long getDataSize();

  /**
   * <code>optional .StorageCloud.HashAlgorithm hashAlgorithm = 2;</code>
   */
  int getHashAlgorithmValue();
  /**
   * <code>optional .StorageCloud.HashAlgorithm hashAlgorithm = 2;</code>
   */
  pl.edu.pw.elka.llepak.tinbox.protobuf.HashAlgorithm getHashAlgorithm();

  /**
   * <code>optional bytes hash = 3;</code>
   */
  com.google.protobuf.ByteString getHash();

  /**
   * <code>optional .StorageCloud.MessageType type = 4;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .StorageCloud.MessageType type = 4;</code>
   */
  pl.edu.pw.elka.llepak.tinbox.protobuf.MessageType getType();

  /**
   * <code>optional bytes data = 5;</code>
   */
  com.google.protobuf.ByteString getData();
}
