// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

/**
 * Protobuf enum {@code StorageCloud.EncryptionAlgorithm}
 */
public enum EncryptionAlgorithm
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>NULL4 = 0;</code>
   */
  NULL4(0),
  /**
   * <code>NOENCRYPTION = 1;</code>
   */
  NOENCRYPTION(1),
  /**
   * <code>CAESAR = 2;</code>
   */
  CAESAR(2),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NULL4 = 0;</code>
   */
  public static final int NULL4_VALUE = 0;
  /**
   * <code>NOENCRYPTION = 1;</code>
   */
  public static final int NOENCRYPTION_VALUE = 1;
  /**
   * <code>CAESAR = 2;</code>
   */
  public static final int CAESAR_VALUE = 2;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static EncryptionAlgorithm valueOf(int value) {
    return forNumber(value);
  }

  public static EncryptionAlgorithm forNumber(int value) {
    switch (value) {
      case 0: return NULL4;
      case 1: return NOENCRYPTION;
      case 2: return CAESAR;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<EncryptionAlgorithm>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      EncryptionAlgorithm> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<EncryptionAlgorithm>() {
          public EncryptionAlgorithm findValueByNumber(int number) {
            return EncryptionAlgorithm.forNumber(number);
          }
        };

  private final int value;

  private EncryptionAlgorithm(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:StorageCloud.EncryptionAlgorithm)
}

