// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

public interface FileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StorageCloud.File)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <pre>
   *with path
   * </pre>
   *
   * <code>optional string filename = 1;</code>
   */
  java.lang.String getFilename();
  /**
   * <pre>
   *with path
   * </pre>
   *
   * <code>optional string filename = 1;</code>
   */
  com.google.protobuf.ByteString
      getFilenameBytes();

  /**
   * <code>optional .StorageCloud.FileType filetype = 2;</code>
   */
  int getFiletypeValue();
  /**
   * <code>optional .StorageCloud.FileType filetype = 2;</code>
   */
  pl.edu.pw.elka.llepak.tinbox.protobuf.FileType getFiletype();

  /**
   * <pre>
   *for directory it's files count inside
   * </pre>
   *
   * <code>optional uint64 size = 3;</code>
   */
  long getSize();

  /**
   * <pre>
   * empty for directory
   * </pre>
   *
   * <code>optional bytes hash = 4;</code>
   */
  com.google.protobuf.ByteString getHash();

  /**
   * <code>optional string owner = 5;</code>
   */
  java.lang.String getOwner();
  /**
   * <code>optional string owner = 5;</code>
   */
  com.google.protobuf.ByteString
      getOwnerBytes();

  /**
   * <code>optional string ownerUsername = 6;</code>
   */
  java.lang.String getOwnerUsername();
  /**
   * <code>optional string ownerUsername = 6;</code>
   */
  com.google.protobuf.ByteString
      getOwnerUsernameBytes();

  /**
   * <code>optional uint64 creationDate = 7;</code>
   */
  long getCreationDate();

  /**
   * <pre>
   * if shared with anyone
   * </pre>
   *
   * <code>optional bool isShared = 8;</code>
   */
  boolean getIsShared();
}
