// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

/**
 * Protobuf type {@code StorageCloud.File}
 */
public  final class File extends
    com.google.protobuf.GeneratedMessageLite<
        File, File.Builder> implements
    // @@protoc_insertion_point(message_implements:StorageCloud.File)
    FileOrBuilder {
  private File() {
    filename_ = "";
    hash_ = com.google.protobuf.ByteString.EMPTY;
    owner_ = "";
    ownerUsername_ = "";
  }
  public static final int FILENAME_FIELD_NUMBER = 1;
  private java.lang.String filename_;
  /**
   * <pre>
   *with path
   * </pre>
   *
   * <code>optional string filename = 1;</code>
   */
  public java.lang.String getFilename() {
    return filename_;
  }
  /**
   * <pre>
   *with path
   * </pre>
   *
   * <code>optional string filename = 1;</code>
   */
  public com.google.protobuf.ByteString
      getFilenameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(filename_);
  }
  /**
   * <pre>
   *with path
   * </pre>
   *
   * <code>optional string filename = 1;</code>
   */
  private void setFilename(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    filename_ = value;
  }
  /**
   * <pre>
   *with path
   * </pre>
   *
   * <code>optional string filename = 1;</code>
   */
  private void clearFilename() {
    
    filename_ = getDefaultInstance().getFilename();
  }
  /**
   * <pre>
   *with path
   * </pre>
   *
   * <code>optional string filename = 1;</code>
   */
  private void setFilenameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    filename_ = value.toStringUtf8();
  }

  public static final int FILETYPE_FIELD_NUMBER = 2;
  private int filetype_;
  /**
   * <code>optional .StorageCloud.FileType filetype = 2;</code>
   */
  public int getFiletypeValue() {
    return filetype_;
  }
  /**
   * <code>optional .StorageCloud.FileType filetype = 2;</code>
   */
  public pl.edu.pw.elka.llepak.tinbox.protobuf.FileType getFiletype() {
    pl.edu.pw.elka.llepak.tinbox.protobuf.FileType result = pl.edu.pw.elka.llepak.tinbox.protobuf.FileType.forNumber(filetype_);
    return result == null ? pl.edu.pw.elka.llepak.tinbox.protobuf.FileType.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .StorageCloud.FileType filetype = 2;</code>
   */
  private void setFiletypeValue(int value) {
      filetype_ = value;
  }
  /**
   * <code>optional .StorageCloud.FileType filetype = 2;</code>
   */
  private void setFiletype(pl.edu.pw.elka.llepak.tinbox.protobuf.FileType value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    filetype_ = value.getNumber();
  }
  /**
   * <code>optional .StorageCloud.FileType filetype = 2;</code>
   */
  private void clearFiletype() {
    
    filetype_ = 0;
  }

  public static final int SIZE_FIELD_NUMBER = 3;
  private long size_;
  /**
   * <pre>
   *for directory it's files count inside
   * </pre>
   *
   * <code>optional uint64 size = 3;</code>
   */
  public long getSize() {
    return size_;
  }
  /**
   * <pre>
   *for directory it's files count inside
   * </pre>
   *
   * <code>optional uint64 size = 3;</code>
   */
  private void setSize(long value) {
    
    size_ = value;
  }
  /**
   * <pre>
   *for directory it's files count inside
   * </pre>
   *
   * <code>optional uint64 size = 3;</code>
   */
  private void clearSize() {
    
    size_ = 0L;
  }

  public static final int HASH_FIELD_NUMBER = 4;
  private com.google.protobuf.ByteString hash_;
  /**
   * <pre>
   * empty for directory
   * </pre>
   *
   * <code>optional bytes hash = 4;</code>
   */
  public com.google.protobuf.ByteString getHash() {
    return hash_;
  }
  /**
   * <pre>
   * empty for directory
   * </pre>
   *
   * <code>optional bytes hash = 4;</code>
   */
  private void setHash(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    hash_ = value;
  }
  /**
   * <pre>
   * empty for directory
   * </pre>
   *
   * <code>optional bytes hash = 4;</code>
   */
  private void clearHash() {
    
    hash_ = getDefaultInstance().getHash();
  }

  public static final int OWNER_FIELD_NUMBER = 5;
  private java.lang.String owner_;
  /**
   * <code>optional string owner = 5;</code>
   */
  public java.lang.String getOwner() {
    return owner_;
  }
  /**
   * <code>optional string owner = 5;</code>
   */
  public com.google.protobuf.ByteString
      getOwnerBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(owner_);
  }
  /**
   * <code>optional string owner = 5;</code>
   */
  private void setOwner(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    owner_ = value;
  }
  /**
   * <code>optional string owner = 5;</code>
   */
  private void clearOwner() {
    
    owner_ = getDefaultInstance().getOwner();
  }
  /**
   * <code>optional string owner = 5;</code>
   */
  private void setOwnerBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    owner_ = value.toStringUtf8();
  }

  public static final int OWNERUSERNAME_FIELD_NUMBER = 6;
  private java.lang.String ownerUsername_;
  /**
   * <code>optional string ownerUsername = 6;</code>
   */
  public java.lang.String getOwnerUsername() {
    return ownerUsername_;
  }
  /**
   * <code>optional string ownerUsername = 6;</code>
   */
  public com.google.protobuf.ByteString
      getOwnerUsernameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(ownerUsername_);
  }
  /**
   * <code>optional string ownerUsername = 6;</code>
   */
  private void setOwnerUsername(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    ownerUsername_ = value;
  }
  /**
   * <code>optional string ownerUsername = 6;</code>
   */
  private void clearOwnerUsername() {
    
    ownerUsername_ = getDefaultInstance().getOwnerUsername();
  }
  /**
   * <code>optional string ownerUsername = 6;</code>
   */
  private void setOwnerUsernameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    ownerUsername_ = value.toStringUtf8();
  }

  public static final int CREATIONDATE_FIELD_NUMBER = 7;
  private long creationDate_;
  /**
   * <code>optional uint64 creationDate = 7;</code>
   */
  public long getCreationDate() {
    return creationDate_;
  }
  /**
   * <code>optional uint64 creationDate = 7;</code>
   */
  private void setCreationDate(long value) {
    
    creationDate_ = value;
  }
  /**
   * <code>optional uint64 creationDate = 7;</code>
   */
  private void clearCreationDate() {
    
    creationDate_ = 0L;
  }

  public static final int ISSHARED_FIELD_NUMBER = 8;
  private boolean isShared_;
  /**
   * <pre>
   * if shared with anyone
   * </pre>
   *
   * <code>optional bool isShared = 8;</code>
   */
  public boolean getIsShared() {
    return isShared_;
  }
  /**
   * <pre>
   * if shared with anyone
   * </pre>
   *
   * <code>optional bool isShared = 8;</code>
   */
  private void setIsShared(boolean value) {
    
    isShared_ = value;
  }
  /**
   * <pre>
   * if shared with anyone
   * </pre>
   *
   * <code>optional bool isShared = 8;</code>
   */
  private void clearIsShared() {
    
    isShared_ = false;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!filename_.isEmpty()) {
      output.writeString(1, getFilename());
    }
    if (filetype_ != pl.edu.pw.elka.llepak.tinbox.protobuf.FileType.NULL6.getNumber()) {
      output.writeEnum(2, filetype_);
    }
    if (size_ != 0L) {
      output.writeUInt64(3, size_);
    }
    if (!hash_.isEmpty()) {
      output.writeBytes(4, hash_);
    }
    if (!owner_.isEmpty()) {
      output.writeString(5, getOwner());
    }
    if (!ownerUsername_.isEmpty()) {
      output.writeString(6, getOwnerUsername());
    }
    if (creationDate_ != 0L) {
      output.writeUInt64(7, creationDate_);
    }
    if (isShared_ != false) {
      output.writeBool(8, isShared_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!filename_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getFilename());
    }
    if (filetype_ != pl.edu.pw.elka.llepak.tinbox.protobuf.FileType.NULL6.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(2, filetype_);
    }
    if (size_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(3, size_);
    }
    if (!hash_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(4, hash_);
    }
    if (!owner_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(5, getOwner());
    }
    if (!ownerUsername_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(6, getOwnerUsername());
    }
    if (creationDate_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeUInt64Size(7, creationDate_);
    }
    if (isShared_ != false) {
      size += com.google.protobuf.CodedOutputStream
        .computeBoolSize(8, isShared_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pl.edu.pw.elka.llepak.tinbox.protobuf.File prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code StorageCloud.File}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        pl.edu.pw.elka.llepak.tinbox.protobuf.File, Builder> implements
      // @@protoc_insertion_point(builder_implements:StorageCloud.File)
      pl.edu.pw.elka.llepak.tinbox.protobuf.FileOrBuilder {
    // Construct using pl.edu.pw.elka.llepak.tinbox.protobuf.File.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <pre>
     *with path
     * </pre>
     *
     * <code>optional string filename = 1;</code>
     */
    public java.lang.String getFilename() {
      return instance.getFilename();
    }
    /**
     * <pre>
     *with path
     * </pre>
     *
     * <code>optional string filename = 1;</code>
     */
    public com.google.protobuf.ByteString
        getFilenameBytes() {
      return instance.getFilenameBytes();
    }
    /**
     * <pre>
     *with path
     * </pre>
     *
     * <code>optional string filename = 1;</code>
     */
    public Builder setFilename(
        java.lang.String value) {
      copyOnWrite();
      instance.setFilename(value);
      return this;
    }
    /**
     * <pre>
     *with path
     * </pre>
     *
     * <code>optional string filename = 1;</code>
     */
    public Builder clearFilename() {
      copyOnWrite();
      instance.clearFilename();
      return this;
    }
    /**
     * <pre>
     *with path
     * </pre>
     *
     * <code>optional string filename = 1;</code>
     */
    public Builder setFilenameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setFilenameBytes(value);
      return this;
    }

    /**
     * <code>optional .StorageCloud.FileType filetype = 2;</code>
     */
    public int getFiletypeValue() {
      return instance.getFiletypeValue();
    }
    /**
     * <code>optional .StorageCloud.FileType filetype = 2;</code>
     */
    public Builder setFiletypeValue(int value) {
      copyOnWrite();
      instance.setFiletypeValue(value);
      return this;
    }
    /**
     * <code>optional .StorageCloud.FileType filetype = 2;</code>
     */
    public pl.edu.pw.elka.llepak.tinbox.protobuf.FileType getFiletype() {
      return instance.getFiletype();
    }
    /**
     * <code>optional .StorageCloud.FileType filetype = 2;</code>
     */
    public Builder setFiletype(pl.edu.pw.elka.llepak.tinbox.protobuf.FileType value) {
      copyOnWrite();
      instance.setFiletype(value);
      return this;
    }
    /**
     * <code>optional .StorageCloud.FileType filetype = 2;</code>
     */
    public Builder clearFiletype() {
      copyOnWrite();
      instance.clearFiletype();
      return this;
    }

    /**
     * <pre>
     *for directory it's files count inside
     * </pre>
     *
     * <code>optional uint64 size = 3;</code>
     */
    public long getSize() {
      return instance.getSize();
    }
    /**
     * <pre>
     *for directory it's files count inside
     * </pre>
     *
     * <code>optional uint64 size = 3;</code>
     */
    public Builder setSize(long value) {
      copyOnWrite();
      instance.setSize(value);
      return this;
    }
    /**
     * <pre>
     *for directory it's files count inside
     * </pre>
     *
     * <code>optional uint64 size = 3;</code>
     */
    public Builder clearSize() {
      copyOnWrite();
      instance.clearSize();
      return this;
    }

    /**
     * <pre>
     * empty for directory
     * </pre>
     *
     * <code>optional bytes hash = 4;</code>
     */
    public com.google.protobuf.ByteString getHash() {
      return instance.getHash();
    }
    /**
     * <pre>
     * empty for directory
     * </pre>
     *
     * <code>optional bytes hash = 4;</code>
     */
    public Builder setHash(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setHash(value);
      return this;
    }
    /**
     * <pre>
     * empty for directory
     * </pre>
     *
     * <code>optional bytes hash = 4;</code>
     */
    public Builder clearHash() {
      copyOnWrite();
      instance.clearHash();
      return this;
    }

    /**
     * <code>optional string owner = 5;</code>
     */
    public java.lang.String getOwner() {
      return instance.getOwner();
    }
    /**
     * <code>optional string owner = 5;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerBytes() {
      return instance.getOwnerBytes();
    }
    /**
     * <code>optional string owner = 5;</code>
     */
    public Builder setOwner(
        java.lang.String value) {
      copyOnWrite();
      instance.setOwner(value);
      return this;
    }
    /**
     * <code>optional string owner = 5;</code>
     */
    public Builder clearOwner() {
      copyOnWrite();
      instance.clearOwner();
      return this;
    }
    /**
     * <code>optional string owner = 5;</code>
     */
    public Builder setOwnerBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOwnerBytes(value);
      return this;
    }

    /**
     * <code>optional string ownerUsername = 6;</code>
     */
    public java.lang.String getOwnerUsername() {
      return instance.getOwnerUsername();
    }
    /**
     * <code>optional string ownerUsername = 6;</code>
     */
    public com.google.protobuf.ByteString
        getOwnerUsernameBytes() {
      return instance.getOwnerUsernameBytes();
    }
    /**
     * <code>optional string ownerUsername = 6;</code>
     */
    public Builder setOwnerUsername(
        java.lang.String value) {
      copyOnWrite();
      instance.setOwnerUsername(value);
      return this;
    }
    /**
     * <code>optional string ownerUsername = 6;</code>
     */
    public Builder clearOwnerUsername() {
      copyOnWrite();
      instance.clearOwnerUsername();
      return this;
    }
    /**
     * <code>optional string ownerUsername = 6;</code>
     */
    public Builder setOwnerUsernameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setOwnerUsernameBytes(value);
      return this;
    }

    /**
     * <code>optional uint64 creationDate = 7;</code>
     */
    public long getCreationDate() {
      return instance.getCreationDate();
    }
    /**
     * <code>optional uint64 creationDate = 7;</code>
     */
    public Builder setCreationDate(long value) {
      copyOnWrite();
      instance.setCreationDate(value);
      return this;
    }
    /**
     * <code>optional uint64 creationDate = 7;</code>
     */
    public Builder clearCreationDate() {
      copyOnWrite();
      instance.clearCreationDate();
      return this;
    }

    /**
     * <pre>
     * if shared with anyone
     * </pre>
     *
     * <code>optional bool isShared = 8;</code>
     */
    public boolean getIsShared() {
      return instance.getIsShared();
    }
    /**
     * <pre>
     * if shared with anyone
     * </pre>
     *
     * <code>optional bool isShared = 8;</code>
     */
    public Builder setIsShared(boolean value) {
      copyOnWrite();
      instance.setIsShared(value);
      return this;
    }
    /**
     * <pre>
     * if shared with anyone
     * </pre>
     *
     * <code>optional bool isShared = 8;</code>
     */
    public Builder clearIsShared() {
      copyOnWrite();
      instance.clearIsShared();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:StorageCloud.File)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new pl.edu.pw.elka.llepak.tinbox.protobuf.File();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        pl.edu.pw.elka.llepak.tinbox.protobuf.File other = (pl.edu.pw.elka.llepak.tinbox.protobuf.File) arg1;
        filename_ = visitor.visitString(!filename_.isEmpty(), filename_,
            !other.filename_.isEmpty(), other.filename_);
        filetype_ = visitor.visitInt(filetype_ != 0, filetype_,    other.filetype_ != 0, other.filetype_);
        size_ = visitor.visitLong(size_ != 0L, size_,
            other.size_ != 0L, other.size_);
        hash_ = visitor.visitByteString(hash_ != com.google.protobuf.ByteString.EMPTY, hash_,
            other.hash_ != com.google.protobuf.ByteString.EMPTY, other.hash_);
        owner_ = visitor.visitString(!owner_.isEmpty(), owner_,
            !other.owner_.isEmpty(), other.owner_);
        ownerUsername_ = visitor.visitString(!ownerUsername_.isEmpty(), ownerUsername_,
            !other.ownerUsername_.isEmpty(), other.ownerUsername_);
        creationDate_ = visitor.visitLong(creationDate_ != 0L, creationDate_,
            other.creationDate_ != 0L, other.creationDate_);
        isShared_ = visitor.visitBoolean(isShared_ != false, isShared_,
            other.isShared_ != false, other.isShared_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                filename_ = s;
                break;
              }
              case 16: {
                int rawValue = input.readEnum();

                filetype_ = rawValue;
                break;
              }
              case 24: {

                size_ = input.readUInt64();
                break;
              }
              case 34: {

                hash_ = input.readBytes();
                break;
              }
              case 42: {
                String s = input.readStringRequireUtf8();

                owner_ = s;
                break;
              }
              case 50: {
                String s = input.readStringRequireUtf8();

                ownerUsername_ = s;
                break;
              }
              case 56: {

                creationDate_ = input.readUInt64();
                break;
              }
              case 64: {

                isShared_ = input.readBool();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (pl.edu.pw.elka.llepak.tinbox.protobuf.File.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:StorageCloud.File)
  private static final pl.edu.pw.elka.llepak.tinbox.protobuf.File DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new File();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<File> PARSER;

  public static com.google.protobuf.Parser<File> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

