// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

/**
 * Protobuf type {@code StorageCloud.File}
 */
public  final class File extends
    com.google.protobuf.GeneratedMessageLite<
        File, File.Builder> implements
    // @@protoc_insertion_point(message_implements:StorageCloud.File)
    FileOrBuilder {
  private File() {
    name_ = "";
    metadata_ = emptyProtobufList();
  }
  private int bitField0_;
  public static final int NAME_FIELD_NUMBER = 1;
  private java.lang.String name_;
  /**
   * <code>optional string name = 1;</code>
   */
  public java.lang.String getName() {
    return name_;
  }
  /**
   * <code>optional string name = 1;</code>
   */
  public com.google.protobuf.ByteString
      getNameBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(name_);
  }
  /**
   * <code>optional string name = 1;</code>
   */
  private void setName(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    name_ = value;
  }
  /**
   * <code>optional string name = 1;</code>
   */
  private void clearName() {
    
    name_ = getDefaultInstance().getName();
  }
  /**
   * <code>optional string name = 1;</code>
   */
  private void setNameBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    name_ = value.toStringUtf8();
  }

  public static final int SIZE_FIELD_NUMBER = 2;
  private long size_;
  /**
   * <code>optional int64 size = 2;</code>
   */
  public long getSize() {
    return size_;
  }
  /**
   * <code>optional int64 size = 2;</code>
   */
  private void setSize(long value) {
    
    size_ = value;
  }
  /**
   * <code>optional int64 size = 2;</code>
   */
  private void clearSize() {
    
    size_ = 0L;
  }

  public static final int METADATA_FIELD_NUMBER = 3;
  private com.google.protobuf.Internal.ProtobufList<pl.edu.pw.elka.llepak.tinbox.protobuf.Param> metadata_;
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  public java.util.List<pl.edu.pw.elka.llepak.tinbox.protobuf.Param> getMetadataList() {
    return metadata_;
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  public java.util.List<? extends pl.edu.pw.elka.llepak.tinbox.protobuf.ParamOrBuilder> 
      getMetadataOrBuilderList() {
    return metadata_;
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  public int getMetadataCount() {
    return metadata_.size();
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  public pl.edu.pw.elka.llepak.tinbox.protobuf.Param getMetadata(int index) {
    return metadata_.get(index);
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  public pl.edu.pw.elka.llepak.tinbox.protobuf.ParamOrBuilder getMetadataOrBuilder(
      int index) {
    return metadata_.get(index);
  }
  private void ensureMetadataIsMutable() {
    if (!metadata_.isModifiable()) {
      metadata_ =
          com.google.protobuf.GeneratedMessageLite.mutableCopy(metadata_);
     }
  }

  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  private void setMetadata(
      int index, pl.edu.pw.elka.llepak.tinbox.protobuf.Param value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureMetadataIsMutable();
    metadata_.set(index, value);
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  private void setMetadata(
      int index, pl.edu.pw.elka.llepak.tinbox.protobuf.Param.Builder builderForValue) {
    ensureMetadataIsMutable();
    metadata_.set(index, builderForValue.build());
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  private void addMetadata(pl.edu.pw.elka.llepak.tinbox.protobuf.Param value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureMetadataIsMutable();
    metadata_.add(value);
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  private void addMetadata(
      int index, pl.edu.pw.elka.llepak.tinbox.protobuf.Param value) {
    if (value == null) {
      throw new NullPointerException();
    }
    ensureMetadataIsMutable();
    metadata_.add(index, value);
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  private void addMetadata(
      pl.edu.pw.elka.llepak.tinbox.protobuf.Param.Builder builderForValue) {
    ensureMetadataIsMutable();
    metadata_.add(builderForValue.build());
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  private void addMetadata(
      int index, pl.edu.pw.elka.llepak.tinbox.protobuf.Param.Builder builderForValue) {
    ensureMetadataIsMutable();
    metadata_.add(index, builderForValue.build());
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  private void addAllMetadata(
      java.lang.Iterable<? extends pl.edu.pw.elka.llepak.tinbox.protobuf.Param> values) {
    ensureMetadataIsMutable();
    com.google.protobuf.AbstractMessageLite.addAll(
        values, metadata_);
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  private void clearMetadata() {
    metadata_ = emptyProtobufList();
  }
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  private void removeMetadata(int index) {
    ensureMetadataIsMutable();
    metadata_.remove(index);
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!name_.isEmpty()) {
      output.writeString(1, getName());
    }
    if (size_ != 0L) {
      output.writeInt64(2, size_);
    }
    for (int i = 0; i < metadata_.size(); i++) {
      output.writeMessage(3, metadata_.get(i));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!name_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getName());
    }
    if (size_ != 0L) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(2, size_);
    }
    for (int i = 0; i < metadata_.size(); i++) {
      size += com.google.protobuf.CodedOutputStream
        .computeMessageSize(3, metadata_.get(i));
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pl.edu.pw.elka.llepak.tinbox.protobuf.File prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code StorageCloud.File}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        pl.edu.pw.elka.llepak.tinbox.protobuf.File, Builder> implements
      // @@protoc_insertion_point(builder_implements:StorageCloud.File)
      pl.edu.pw.elka.llepak.tinbox.protobuf.FileOrBuilder {
    // Construct using pl.edu.pw.elka.llepak.tinbox.protobuf.File.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional string name = 1;</code>
     */
    public java.lang.String getName() {
      return instance.getName();
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public com.google.protobuf.ByteString
        getNameBytes() {
      return instance.getNameBytes();
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setName(
        java.lang.String value) {
      copyOnWrite();
      instance.setName(value);
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder clearName() {
      copyOnWrite();
      instance.clearName();
      return this;
    }
    /**
     * <code>optional string name = 1;</code>
     */
    public Builder setNameBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setNameBytes(value);
      return this;
    }

    /**
     * <code>optional int64 size = 2;</code>
     */
    public long getSize() {
      return instance.getSize();
    }
    /**
     * <code>optional int64 size = 2;</code>
     */
    public Builder setSize(long value) {
      copyOnWrite();
      instance.setSize(value);
      return this;
    }
    /**
     * <code>optional int64 size = 2;</code>
     */
    public Builder clearSize() {
      copyOnWrite();
      instance.clearSize();
      return this;
    }

    /**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public java.util.List<pl.edu.pw.elka.llepak.tinbox.protobuf.Param> getMetadataList() {
      return java.util.Collections.unmodifiableList(
          instance.getMetadataList());
    }
    /**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public int getMetadataCount() {
      return instance.getMetadataCount();
    }/**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public pl.edu.pw.elka.llepak.tinbox.protobuf.Param getMetadata(int index) {
      return instance.getMetadata(index);
    }
    /**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public Builder setMetadata(
        int index, pl.edu.pw.elka.llepak.tinbox.protobuf.Param value) {
      copyOnWrite();
      instance.setMetadata(index, value);
      return this;
    }
    /**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public Builder setMetadata(
        int index, pl.edu.pw.elka.llepak.tinbox.protobuf.Param.Builder builderForValue) {
      copyOnWrite();
      instance.setMetadata(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public Builder addMetadata(pl.edu.pw.elka.llepak.tinbox.protobuf.Param value) {
      copyOnWrite();
      instance.addMetadata(value);
      return this;
    }
    /**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public Builder addMetadata(
        int index, pl.edu.pw.elka.llepak.tinbox.protobuf.Param value) {
      copyOnWrite();
      instance.addMetadata(index, value);
      return this;
    }
    /**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public Builder addMetadata(
        pl.edu.pw.elka.llepak.tinbox.protobuf.Param.Builder builderForValue) {
      copyOnWrite();
      instance.addMetadata(builderForValue);
      return this;
    }
    /**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public Builder addMetadata(
        int index, pl.edu.pw.elka.llepak.tinbox.protobuf.Param.Builder builderForValue) {
      copyOnWrite();
      instance.addMetadata(index, builderForValue);
      return this;
    }
    /**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public Builder addAllMetadata(
        java.lang.Iterable<? extends pl.edu.pw.elka.llepak.tinbox.protobuf.Param> values) {
      copyOnWrite();
      instance.addAllMetadata(values);
      return this;
    }
    /**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public Builder clearMetadata() {
      copyOnWrite();
      instance.clearMetadata();
      return this;
    }
    /**
     * <code>repeated .StorageCloud.Param metadata = 3;</code>
     */
    public Builder removeMetadata(int index) {
      copyOnWrite();
      instance.removeMetadata(index);
      return this;
    }

    // @@protoc_insertion_point(builder_scope:StorageCloud.File)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new pl.edu.pw.elka.llepak.tinbox.protobuf.File();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        metadata_.makeImmutable();
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        pl.edu.pw.elka.llepak.tinbox.protobuf.File other = (pl.edu.pw.elka.llepak.tinbox.protobuf.File) arg1;
        name_ = visitor.visitString(!name_.isEmpty(), name_,
            !other.name_.isEmpty(), other.name_);
        size_ = visitor.visitLong(size_ != 0L, size_,
            other.size_ != 0L, other.size_);
        metadata_= visitor.visitList(metadata_, other.metadata_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          bitField0_ |= other.bitField0_;
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                name_ = s;
                break;
              }
              case 16: {

                size_ = input.readInt64();
                break;
              }
              case 26: {
                if (!metadata_.isModifiable()) {
                  metadata_ =
                      com.google.protobuf.GeneratedMessageLite.mutableCopy(metadata_);
                }
                metadata_.add(
                    input.readMessage(pl.edu.pw.elka.llepak.tinbox.protobuf.Param.parser(), extensionRegistry));
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (pl.edu.pw.elka.llepak.tinbox.protobuf.File.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:StorageCloud.File)
  private static final pl.edu.pw.elka.llepak.tinbox.protobuf.File DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new File();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static pl.edu.pw.elka.llepak.tinbox.protobuf.File getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<File> PARSER;

  public static com.google.protobuf.Parser<File> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

