// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

public interface FileOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StorageCloud.File)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string name = 1;</code>
   */
  java.lang.String getName();
  /**
   * <code>optional string name = 1;</code>
   */
  com.google.protobuf.ByteString
      getNameBytes();

  /**
   * <code>optional int64 size = 2;</code>
   */
  long getSize();

  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  java.util.List<pl.edu.pw.elka.llepak.tinbox.protobuf.Param> 
      getMetadataList();
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  pl.edu.pw.elka.llepak.tinbox.protobuf.Param getMetadata(int index);
  /**
   * <code>repeated .StorageCloud.Param metadata = 3;</code>
   */
  int getMetadataCount();
}
