// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

public interface HandshakeOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StorageCloud.Handshake)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
   */
  int getEncryptionAlgorithmValue();
  /**
   * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
   */
  pl.edu.pw.elka.llepak.tinbox.protobuf.EncryptionAlgorithm getEncryptionAlgorithm();
}
