// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

/**
 * Protobuf type {@code StorageCloud.Handshake}
 */
public  final class Handshake extends
    com.google.protobuf.GeneratedMessageLite<
        Handshake, Handshake.Builder> implements
    // @@protoc_insertion_point(message_implements:StorageCloud.Handshake)
    HandshakeOrBuilder {
  private Handshake() {
  }
  public static final int ENCRYPTIONALGORITHM_FIELD_NUMBER = 1;
  private int encryptionAlgorithm_;
  /**
   * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
   */
  public int getEncryptionAlgorithmValue() {
    return encryptionAlgorithm_;
  }
  /**
   * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
   */
  public pl.edu.pw.elka.llepak.tinbox.protobuf.EncryptionAlgorithm getEncryptionAlgorithm() {
    pl.edu.pw.elka.llepak.tinbox.protobuf.EncryptionAlgorithm result = pl.edu.pw.elka.llepak.tinbox.protobuf.EncryptionAlgorithm.forNumber(encryptionAlgorithm_);
    return result == null ? pl.edu.pw.elka.llepak.tinbox.protobuf.EncryptionAlgorithm.UNRECOGNIZED : result;
  }
  /**
   * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
   */
  private void setEncryptionAlgorithmValue(int value) {
      encryptionAlgorithm_ = value;
  }
  /**
   * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
   */
  private void setEncryptionAlgorithm(pl.edu.pw.elka.llepak.tinbox.protobuf.EncryptionAlgorithm value) {
    if (value == null) {
      throw new NullPointerException();
    }
    
    encryptionAlgorithm_ = value.getNumber();
  }
  /**
   * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
   */
  private void clearEncryptionAlgorithm() {
    
    encryptionAlgorithm_ = 0;
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (encryptionAlgorithm_ != pl.edu.pw.elka.llepak.tinbox.protobuf.EncryptionAlgorithm.NULL4.getNumber()) {
      output.writeEnum(1, encryptionAlgorithm_);
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (encryptionAlgorithm_ != pl.edu.pw.elka.llepak.tinbox.protobuf.EncryptionAlgorithm.NULL4.getNumber()) {
      size += com.google.protobuf.CodedOutputStream
        .computeEnumSize(1, encryptionAlgorithm_);
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code StorageCloud.Handshake}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake, Builder> implements
      // @@protoc_insertion_point(builder_implements:StorageCloud.Handshake)
      pl.edu.pw.elka.llepak.tinbox.protobuf.HandshakeOrBuilder {
    // Construct using pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }


    /**
     * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
     */
    public int getEncryptionAlgorithmValue() {
      return instance.getEncryptionAlgorithmValue();
    }
    /**
     * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
     */
    public Builder setEncryptionAlgorithmValue(int value) {
      copyOnWrite();
      instance.setEncryptionAlgorithmValue(value);
      return this;
    }
    /**
     * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
     */
    public pl.edu.pw.elka.llepak.tinbox.protobuf.EncryptionAlgorithm getEncryptionAlgorithm() {
      return instance.getEncryptionAlgorithm();
    }
    /**
     * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
     */
    public Builder setEncryptionAlgorithm(pl.edu.pw.elka.llepak.tinbox.protobuf.EncryptionAlgorithm value) {
      copyOnWrite();
      instance.setEncryptionAlgorithm(value);
      return this;
    }
    /**
     * <code>optional .StorageCloud.EncryptionAlgorithm encryptionAlgorithm = 1;</code>
     */
    public Builder clearEncryptionAlgorithm() {
      copyOnWrite();
      instance.clearEncryptionAlgorithm();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:StorageCloud.Handshake)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake other = (pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake) arg1;
        encryptionAlgorithm_ = visitor.visitInt(encryptionAlgorithm_ != 0, encryptionAlgorithm_,    other.encryptionAlgorithm_ != 0, other.encryptionAlgorithm_);
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 8: {
                int rawValue = input.readEnum();

                encryptionAlgorithm_ = rawValue;
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:StorageCloud.Handshake)
  private static final pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Handshake();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Handshake getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Handshake> PARSER;

  public static com.google.protobuf.Parser<Handshake> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

