// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

/**
 * Protobuf enum {@code StorageCloud.HashAlgorithm}
 */
public enum HashAlgorithm
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>NULL2 = 0;</code>
   */
  NULL2(0),
  /**
   * <code>H_NOHASH = 1;</code>
   */
  H_NOHASH(1),
  /**
   * <code>H_SHA256 = 2;</code>
   */
  H_SHA256(2),
  /**
   * <code>H_SHA512 = 3;</code>
   */
  H_SHA512(3),
  /**
   * <code>H_SHA1 = 4;</code>
   */
  H_SHA1(4),
  /**
   * <code>H_MD5 = 5;</code>
   */
  H_MD5(5),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NULL2 = 0;</code>
   */
  public static final int NULL2_VALUE = 0;
  /**
   * <code>H_NOHASH = 1;</code>
   */
  public static final int H_NOHASH_VALUE = 1;
  /**
   * <code>H_SHA256 = 2;</code>
   */
  public static final int H_SHA256_VALUE = 2;
  /**
   * <code>H_SHA512 = 3;</code>
   */
  public static final int H_SHA512_VALUE = 3;
  /**
   * <code>H_SHA1 = 4;</code>
   */
  public static final int H_SHA1_VALUE = 4;
  /**
   * <code>H_MD5 = 5;</code>
   */
  public static final int H_MD5_VALUE = 5;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static HashAlgorithm valueOf(int value) {
    return forNumber(value);
  }

  public static HashAlgorithm forNumber(int value) {
    switch (value) {
      case 0: return NULL2;
      case 1: return H_NOHASH;
      case 2: return H_SHA256;
      case 3: return H_SHA512;
      case 4: return H_SHA1;
      case 5: return H_MD5;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<HashAlgorithm>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      HashAlgorithm> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<HashAlgorithm>() {
          public HashAlgorithm findValueByNumber(int number) {
            return HashAlgorithm.forNumber(number);
          }
        };

  private final int value;

  private HashAlgorithm(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:StorageCloud.HashAlgorithm)
}

