// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

/**
 * Protobuf enum {@code StorageCloud.MessageType}
 */
public enum MessageType
    implements com.google.protobuf.Internal.EnumLite {
  /**
   * <code>NULL3 = 0;</code>
   */
  NULL3(0),
  /**
   * <code>COMMAND = 1;</code>
   */
  COMMAND(1),
  /**
   * <code>SERVER_RESPONSE = 2;</code>
   */
  SERVER_RESPONSE(2),
  /**
   * <code>HANDSHAKE = 3;</code>
   */
  HANDSHAKE(3),
  UNRECOGNIZED(-1),
  ;

  /**
   * <code>NULL3 = 0;</code>
   */
  public static final int NULL3_VALUE = 0;
  /**
   * <code>COMMAND = 1;</code>
   */
  public static final int COMMAND_VALUE = 1;
  /**
   * <code>SERVER_RESPONSE = 2;</code>
   */
  public static final int SERVER_RESPONSE_VALUE = 2;
  /**
   * <code>HANDSHAKE = 3;</code>
   */
  public static final int HANDSHAKE_VALUE = 3;


  public final int getNumber() {
    return value;
  }

  /**
   * @deprecated Use {@link #forNumber(int)} instead.
   */
  @java.lang.Deprecated
  public static MessageType valueOf(int value) {
    return forNumber(value);
  }

  public static MessageType forNumber(int value) {
    switch (value) {
      case 0: return NULL3;
      case 1: return COMMAND;
      case 2: return SERVER_RESPONSE;
      case 3: return HANDSHAKE;
      default: return null;
    }
  }

  public static com.google.protobuf.Internal.EnumLiteMap<MessageType>
      internalGetValueMap() {
    return internalValueMap;
  }
  private static final com.google.protobuf.Internal.EnumLiteMap<
      MessageType> internalValueMap =
        new com.google.protobuf.Internal.EnumLiteMap<MessageType>() {
          public MessageType findValueByNumber(int number) {
            return MessageType.forNumber(number);
          }
        };

  private final int value;

  private MessageType(int value) {
    this.value = value;
  }

  // @@protoc_insertion_point(enum_scope:StorageCloud.MessageType)
}

