// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

/**
 * Protobuf type {@code StorageCloud.Param}
 */
public  final class Param extends
    com.google.protobuf.GeneratedMessageLite<
        Param, Param.Builder> implements
    // @@protoc_insertion_point(message_implements:StorageCloud.Param)
    ParamOrBuilder {
  private Param() {
    paramId_ = "";
  }
  private int valueCase_ = 0;
  private java.lang.Object value_;
  public enum ValueCase
      implements com.google.protobuf.Internal.EnumLite {
    SPARAMVAL(2),
    IPARAMVAL(3),
    BPARAMVAL(4),
    VALUE_NOT_SET(0);
    private final int value;
    private ValueCase(int value) {
      this.value = value;
    }
    /**
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static ValueCase valueOf(int value) {
      return forNumber(value);
    }

    public static ValueCase forNumber(int value) {
      switch (value) {
        case 2: return SPARAMVAL;
        case 3: return IPARAMVAL;
        case 4: return BPARAMVAL;
        case 0: return VALUE_NOT_SET;
        default: return null;
      }
    }
    public int getNumber() {
      return this.value;
    }
  };

  public ValueCase
  getValueCase() {
    return ValueCase.forNumber(
        valueCase_);
  }

  private void clearValue() {
    valueCase_ = 0;
    value_ = null;
  }

  public static final int PARAMID_FIELD_NUMBER = 1;
  private java.lang.String paramId_;
  /**
   * <code>optional string paramId = 1;</code>
   */
  public java.lang.String getParamId() {
    return paramId_;
  }
  /**
   * <code>optional string paramId = 1;</code>
   */
  public com.google.protobuf.ByteString
      getParamIdBytes() {
    return com.google.protobuf.ByteString.copyFromUtf8(paramId_);
  }
  /**
   * <code>optional string paramId = 1;</code>
   */
  private void setParamId(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  
    paramId_ = value;
  }
  /**
   * <code>optional string paramId = 1;</code>
   */
  private void clearParamId() {
    
    paramId_ = getDefaultInstance().getParamId();
  }
  /**
   * <code>optional string paramId = 1;</code>
   */
  private void setParamIdBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    
    paramId_ = value.toStringUtf8();
  }

  public static final int SPARAMVAL_FIELD_NUMBER = 2;
  /**
   * <code>optional string SParamVal = 2;</code>
   */
  public java.lang.String getSParamVal() {
    java.lang.String ref = "";
    if (valueCase_ == 2) {
      ref = (java.lang.String) value_;
    }
    return ref;
  }
  /**
   * <code>optional string SParamVal = 2;</code>
   */
  public com.google.protobuf.ByteString
      getSParamValBytes() {
    java.lang.String ref = "";
    if (valueCase_ == 2) {
      ref = (java.lang.String) value_;
    }
    return com.google.protobuf.ByteString.copyFromUtf8(ref);
  }
  /**
   * <code>optional string SParamVal = 2;</code>
   */
  private void setSParamVal(
      java.lang.String value) {
    if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 2;
    value_ = value;
  }
  /**
   * <code>optional string SParamVal = 2;</code>
   */
  private void clearSParamVal() {
    if (valueCase_ == 2) {
      valueCase_ = 0;
      value_ = null;
    }
  }
  /**
   * <code>optional string SParamVal = 2;</code>
   */
  private void setSParamValBytes(
      com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
    valueCase_ = 2;
    value_ = value.toStringUtf8();
  }

  public static final int IPARAMVAL_FIELD_NUMBER = 3;
  /**
   * <code>optional int64 IParamVal = 3;</code>
   */
  public long getIParamVal() {
    if (valueCase_ == 3) {
      return (java.lang.Long) value_;
    }
    return 0L;
  }
  /**
   * <code>optional int64 IParamVal = 3;</code>
   */
  private void setIParamVal(long value) {
    valueCase_ = 3;
    value_ = value;
  }
  /**
   * <code>optional int64 IParamVal = 3;</code>
   */
  private void clearIParamVal() {
    if (valueCase_ == 3) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public static final int BPARAMVAL_FIELD_NUMBER = 4;
  /**
   * <code>optional bytes BParamVal = 4;</code>
   */
  public com.google.protobuf.ByteString getBParamVal() {
    if (valueCase_ == 4) {
      return (com.google.protobuf.ByteString) value_;
    }
    return com.google.protobuf.ByteString.EMPTY;
  }
  /**
   * <code>optional bytes BParamVal = 4;</code>
   */
  private void setBParamVal(com.google.protobuf.ByteString value) {
    if (value == null) {
    throw new NullPointerException();
  }
  valueCase_ = 4;
    value_ = value;
  }
  /**
   * <code>optional bytes BParamVal = 4;</code>
   */
  private void clearBParamVal() {
    if (valueCase_ == 4) {
      valueCase_ = 0;
      value_ = null;
    }
  }

  public void writeTo(com.google.protobuf.CodedOutputStream output)
                      throws java.io.IOException {
    if (!paramId_.isEmpty()) {
      output.writeString(1, getParamId());
    }
    if (valueCase_ == 2) {
      output.writeString(2, getSParamVal());
    }
    if (valueCase_ == 3) {
      output.writeInt64(
          3, (long)((java.lang.Long) value_));
    }
    if (valueCase_ == 4) {
      output.writeBytes(
          4, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
    }
  }

  public int getSerializedSize() {
    int size = memoizedSerializedSize;
    if (size != -1) return size;

    size = 0;
    if (!paramId_.isEmpty()) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(1, getParamId());
    }
    if (valueCase_ == 2) {
      size += com.google.protobuf.CodedOutputStream
        .computeStringSize(2, getSParamVal());
    }
    if (valueCase_ == 3) {
      size += com.google.protobuf.CodedOutputStream
        .computeInt64Size(
            3, (long)((java.lang.Long) value_));
    }
    if (valueCase_ == 4) {
      size += com.google.protobuf.CodedOutputStream
        .computeBytesSize(
            4, (com.google.protobuf.ByteString)((com.google.protobuf.ByteString) value_));
    }
    memoizedSerializedSize = size;
    return size;
  }

  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Param parseFrom(
      com.google.protobuf.ByteString data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Param parseFrom(
      com.google.protobuf.ByteString data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Param parseFrom(byte[] data)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Param parseFrom(
      byte[] data,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws com.google.protobuf.InvalidProtocolBufferException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, data, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Param parseFrom(java.io.InputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Param parseFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Param parseDelimitedFrom(java.io.InputStream input)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Param parseDelimitedFrom(
      java.io.InputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return parseDelimitedFrom(DEFAULT_INSTANCE, input, extensionRegistry);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Param parseFrom(
      com.google.protobuf.CodedInputStream input)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input);
  }
  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Param parseFrom(
      com.google.protobuf.CodedInputStream input,
      com.google.protobuf.ExtensionRegistryLite extensionRegistry)
      throws java.io.IOException {
    return com.google.protobuf.GeneratedMessageLite.parseFrom(
        DEFAULT_INSTANCE, input, extensionRegistry);
  }

  public static Builder newBuilder() {
    return DEFAULT_INSTANCE.toBuilder();
  }
  public static Builder newBuilder(pl.edu.pw.elka.llepak.tinbox.protobuf.Param prototype) {
    return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
  }

  /**
   * Protobuf type {@code StorageCloud.Param}
   */
  public static final class Builder extends
      com.google.protobuf.GeneratedMessageLite.Builder<
        pl.edu.pw.elka.llepak.tinbox.protobuf.Param, Builder> implements
      // @@protoc_insertion_point(builder_implements:StorageCloud.Param)
      pl.edu.pw.elka.llepak.tinbox.protobuf.ParamOrBuilder {
    // Construct using pl.edu.pw.elka.llepak.tinbox.protobuf.Param.newBuilder()
    private Builder() {
      super(DEFAULT_INSTANCE);
    }

    public ValueCase
        getValueCase() {
      return instance.getValueCase();
    }

    public Builder clearValue() {
      copyOnWrite();
      instance.clearValue();
      return this;
    }


    /**
     * <code>optional string paramId = 1;</code>
     */
    public java.lang.String getParamId() {
      return instance.getParamId();
    }
    /**
     * <code>optional string paramId = 1;</code>
     */
    public com.google.protobuf.ByteString
        getParamIdBytes() {
      return instance.getParamIdBytes();
    }
    /**
     * <code>optional string paramId = 1;</code>
     */
    public Builder setParamId(
        java.lang.String value) {
      copyOnWrite();
      instance.setParamId(value);
      return this;
    }
    /**
     * <code>optional string paramId = 1;</code>
     */
    public Builder clearParamId() {
      copyOnWrite();
      instance.clearParamId();
      return this;
    }
    /**
     * <code>optional string paramId = 1;</code>
     */
    public Builder setParamIdBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setParamIdBytes(value);
      return this;
    }

    /**
     * <code>optional string SParamVal = 2;</code>
     */
    public java.lang.String getSParamVal() {
      return instance.getSParamVal();
    }
    /**
     * <code>optional string SParamVal = 2;</code>
     */
    public com.google.protobuf.ByteString
        getSParamValBytes() {
      return instance.getSParamValBytes();
    }
    /**
     * <code>optional string SParamVal = 2;</code>
     */
    public Builder setSParamVal(
        java.lang.String value) {
      copyOnWrite();
      instance.setSParamVal(value);
      return this;
    }
    /**
     * <code>optional string SParamVal = 2;</code>
     */
    public Builder clearSParamVal() {
      copyOnWrite();
      instance.clearSParamVal();
      return this;
    }
    /**
     * <code>optional string SParamVal = 2;</code>
     */
    public Builder setSParamValBytes(
        com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setSParamValBytes(value);
      return this;
    }

    /**
     * <code>optional int64 IParamVal = 3;</code>
     */
    public long getIParamVal() {
      return instance.getIParamVal();
    }
    /**
     * <code>optional int64 IParamVal = 3;</code>
     */
    public Builder setIParamVal(long value) {
      copyOnWrite();
      instance.setIParamVal(value);
      return this;
    }
    /**
     * <code>optional int64 IParamVal = 3;</code>
     */
    public Builder clearIParamVal() {
      copyOnWrite();
      instance.clearIParamVal();
      return this;
    }

    /**
     * <code>optional bytes BParamVal = 4;</code>
     */
    public com.google.protobuf.ByteString getBParamVal() {
      return instance.getBParamVal();
    }
    /**
     * <code>optional bytes BParamVal = 4;</code>
     */
    public Builder setBParamVal(com.google.protobuf.ByteString value) {
      copyOnWrite();
      instance.setBParamVal(value);
      return this;
    }
    /**
     * <code>optional bytes BParamVal = 4;</code>
     */
    public Builder clearBParamVal() {
      copyOnWrite();
      instance.clearBParamVal();
      return this;
    }

    // @@protoc_insertion_point(builder_scope:StorageCloud.Param)
  }
  protected final Object dynamicMethod(
      com.google.protobuf.GeneratedMessageLite.MethodToInvoke method,
      Object arg0, Object arg1) {
    switch (method) {
      case NEW_MUTABLE_INSTANCE: {
        return new pl.edu.pw.elka.llepak.tinbox.protobuf.Param();
      }
      case IS_INITIALIZED: {
        return DEFAULT_INSTANCE;
      }
      case MAKE_IMMUTABLE: {
        return null;
      }
      case NEW_BUILDER: {
        return new Builder();
      }
      case VISIT: {
        Visitor visitor = (Visitor) arg0;
        pl.edu.pw.elka.llepak.tinbox.protobuf.Param other = (pl.edu.pw.elka.llepak.tinbox.protobuf.Param) arg1;
        paramId_ = visitor.visitString(!paramId_.isEmpty(), paramId_,
            !other.paramId_.isEmpty(), other.paramId_);
        switch (other.getValueCase()) {
          case SPARAMVAL: {
            value_ = visitor.visitOneofString(
               valueCase_ == 2, value_, other.value_);
            break;
          }
          case IPARAMVAL: {
            value_ = visitor.visitOneofLong(
                valueCase_ == 3, value_, other.value_);
            break;
          }
          case BPARAMVAL: {
            value_ = visitor.visitOneofByteString(
                valueCase_ == 4, value_, other.value_);
            break;
          }
          case VALUE_NOT_SET: {
            visitor.visitOneofNotSet(valueCase_ != 0);
            break;
          }
        }
        if (visitor == com.google.protobuf.GeneratedMessageLite.MergeFromVisitor
            .INSTANCE) {
          if (other.valueCase_ != 0) {
            valueCase_ = other.valueCase_;
          }
        }
        return this;
      }
      case MERGE_FROM_STREAM: {
        com.google.protobuf.CodedInputStream input =
            (com.google.protobuf.CodedInputStream) arg0;
        com.google.protobuf.ExtensionRegistryLite extensionRegistry =
            (com.google.protobuf.ExtensionRegistryLite) arg1;
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              default: {
                if (!input.skipField(tag)) {
                  done = true;
                }
                break;
              }
              case 10: {
                String s = input.readStringRequireUtf8();

                paramId_ = s;
                break;
              }
              case 18: {
                String s = input.readStringRequireUtf8();
                valueCase_ = 2;
                value_ = s;
                break;
              }
              case 24: {
                valueCase_ = 3;
                value_ = input.readInt64();
                break;
              }
              case 34: {
                valueCase_ = 4;
                value_ = input.readBytes();
                break;
              }
            }
          }
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw new RuntimeException(e.setUnfinishedMessage(this));
        } catch (java.io.IOException e) {
          throw new RuntimeException(
              new com.google.protobuf.InvalidProtocolBufferException(
                  e.getMessage()).setUnfinishedMessage(this));
        } finally {
        }
      }
      case GET_DEFAULT_INSTANCE: {
        return DEFAULT_INSTANCE;
      }
      case GET_PARSER: {
        if (PARSER == null) {    synchronized (pl.edu.pw.elka.llepak.tinbox.protobuf.Param.class) {
            if (PARSER == null) {
              PARSER = new DefaultInstanceBasedParser(DEFAULT_INSTANCE);
            }
          }
        }
        return PARSER;
      }
    }
    throw new UnsupportedOperationException();
  }


  // @@protoc_insertion_point(class_scope:StorageCloud.Param)
  private static final pl.edu.pw.elka.llepak.tinbox.protobuf.Param DEFAULT_INSTANCE;
  static {
    DEFAULT_INSTANCE = new Param();
    DEFAULT_INSTANCE.makeImmutable();
  }

  public static pl.edu.pw.elka.llepak.tinbox.protobuf.Param getDefaultInstance() {
    return DEFAULT_INSTANCE;
  }

  private static volatile com.google.protobuf.Parser<Param> PARSER;

  public static com.google.protobuf.Parser<Param> parser() {
    return DEFAULT_INSTANCE.getParserForType();
  }
}

