// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

public interface ParamOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StorageCloud.Param)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional string paramId = 1;</code>
   */
  java.lang.String getParamId();
  /**
   * <code>optional string paramId = 1;</code>
   */
  com.google.protobuf.ByteString
      getParamIdBytes();

  /**
   * <code>optional string SParamVal = 2;</code>
   */
  java.lang.String getSParamVal();
  /**
   * <code>optional string SParamVal = 2;</code>
   */
  com.google.protobuf.ByteString
      getSParamValBytes();

  /**
   * <code>optional int64 IParamVal = 3;</code>
   */
  long getIParamVal();

  /**
   * <code>optional bytes BParamVal = 4;</code>
   */
  com.google.protobuf.ByteString getBParamVal();

  public pl.edu.pw.elka.llepak.tinbox.protobuf.Param.ValueCase getValueCase();
}
