// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: messages.proto

package pl.edu.pw.elka.llepak.tinbox.protobuf;

public interface ServerResponseOrBuilder extends
    // @@protoc_insertion_point(interface_extends:StorageCloud.ServerResponse)
    com.google.protobuf.MessageLiteOrBuilder {

  /**
   * <code>optional .StorageCloud.ResponseType type = 1;</code>
   */
  int getTypeValue();
  /**
   * <code>optional .StorageCloud.ResponseType type = 1;</code>
   */
  pl.edu.pw.elka.llepak.tinbox.protobuf.ResponseType getType();

  /**
   * <code>repeated .StorageCloud.Param params = 2;</code>
   */
  java.util.List<pl.edu.pw.elka.llepak.tinbox.protobuf.Param> 
      getParamsList();
  /**
   * <code>repeated .StorageCloud.Param params = 2;</code>
   */
  pl.edu.pw.elka.llepak.tinbox.protobuf.Param getParams(int index);
  /**
   * <code>repeated .StorageCloud.Param params = 2;</code>
   */
  int getParamsCount();

  /**
   * <code>repeated string list = 3;</code>
   */
  java.util.List<String>
      getListList();
  /**
   * <code>repeated string list = 3;</code>
   */
  int getListCount();
  /**
   * <code>repeated string list = 3;</code>
   */
  java.lang.String getList(int index);
  /**
   * <code>repeated string list = 3;</code>
   */
  com.google.protobuf.ByteString
      getListBytes(int index);

  /**
   * <code>repeated .StorageCloud.File fileList = 4;</code>
   */
  java.util.List<pl.edu.pw.elka.llepak.tinbox.protobuf.File> 
      getFileListList();
  /**
   * <code>repeated .StorageCloud.File fileList = 4;</code>
   */
  pl.edu.pw.elka.llepak.tinbox.protobuf.File getFileList(int index);
  /**
   * <code>repeated .StorageCloud.File fileList = 4;</code>
   */
  int getFileListCount();

  /**
   * <code>repeated .StorageCloud.UserDetails userList = 5;</code>
   */
  java.util.List<pl.edu.pw.elka.llepak.tinbox.protobuf.UserDetails> 
      getUserListList();
  /**
   * <code>repeated .StorageCloud.UserDetails userList = 5;</code>
   */
  pl.edu.pw.elka.llepak.tinbox.protobuf.UserDetails getUserList(int index);
  /**
   * <code>repeated .StorageCloud.UserDetails userList = 5;</code>
   */
  int getUserListCount();

  /**
   * <code>optional bytes data = 6;</code>
   */
  com.google.protobuf.ByteString getData();
}
